[output]
feature-depth = 1

[licenses]
allow = [
    "MIT",
    "Unicode-3.0",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "GPL-3.0",
    "Zlib"
]
confidence-threshold = 1.0

[licenses.private]
ignore = false
registries = [
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []